### PR TITLE
Added crops-dev target based upon linuxtools 5.2, Eclipse neon.2, CDT

### PR DESCRIPTION
**Pull request by scottslewis**
Hi Tim and Brian,

Here's a crops-dev.target file added to releng with target consisting of linuxtools 5.2, linuxtools docker support, CDT 9.2 and eclipse neon.2 deps.  Also includes sources of appropriate versions...for docker support.   I'm able to resolve and run this target successfully in neon.2.   If either of you are not for whatever reason let me know and I will fix and resubmit pull request off of my fork.

### CODE REVIEW

**Comment by bavery22** [comment]
Hi, 

I had some resolution issues. I tried it with just the eclipse-crops as a ws project and with all the cdt and linuxtools projects pulled in.

Here's a screenshot: https://www.dropbox.com/s/lyrr3vypyodu2pw/Screen%20Shot%202016-12-27%20at%2012.32.54%20PM.png?dl=0

What am I doing wrong? :)
This was using crops-dev.target.

**Comment by moto-timo** [comment]
It's refusing to install system tap on Mac OS X because it is flagged as Linux only.

**Comment by scottslewis** [comment]
Hi Brian.  It appears that you might be using some non neon.2 version of
eclipse?  As it is having an environment problem with Linux tools systemtap
v5.2.0.  Is there any more detail with error message?...it's not fully
visible on right.

Fwiw I started with plain 'ol neon.2 eclipse sdk before resolving this
target

**Comment by bavery22** [comment]
I was on the Mac.

I'll try looking it on Linux this afternoon.
B

**Comment by bavery22** [comment]
This did resolve for me on Linux.  Mine was still missing org.eclipse.tools.templates.freemarker net.sourceforge.lpg.lpgiavaruntime.  The main effect seems to be that the cmake project is not available.  We can merge and deal with mac and the missing dependencies moving forward.

**Comment by moto-timo** [comment]
Some of the components in LinuxTools are Linux only, so we may need to pick and choose. Most of the non-Docker components (e.g. not in the /containers directory ) are there for performance and profile testing. Ultimately we need a core set that is platform agnostic, with a possible superset that is Linux specific.

**Pull request merged**
